# Source: internal/cmdrunner/cmd_reattach.go
Feature: Command Reattachment Logic

  Background:
    Reattaching to an existing plugin process requires careful validation to ensure the correct process is targeted.
    Platform differences in process handling and network dialing can affect reattachment success.

  Scenario: ReattachFunc successfully finds and validates an existing plugin process
    Given a plugin process is running with PID <PID>
    And this plugin is listening on network address <Network> at <Address>
    When the ReattachFunc generated by `ReattachFunc(<PID>, "<Network>:<Address>")` is invoked
    Then `os.FindProcess(<PID>)` should succeed in finding a process handle
    And a `net.Dial("<Network>", "<Address>")` should succeed
    And a `CmdAttachedRunner` instance should be returned, configured with <PID> and the process handle
    And no error should be returned by the ReattachFunc

  Scenario: ReattachFunc fails if os.FindProcess fails (e.g., Windows, PID does not exist)
    Given a PID <NonExistentPID> that does not correspond to a running process
    And a network address <Network> at <Address>
    And the current platform is Windows (where FindProcess can error for non-existent PIDs)
    When the ReattachFunc generated by `ReattachFunc(<NonExistentPID>, "<Network>:<Address>")` is invoked
    Then `os.FindProcess(<NonExistentPID>)` should fail
    And the ReattachFunc should return an `ErrProcessNotFound` error

  Scenario: ReattachFunc fails if net.Dial fails (process found but not listening or wrong process)
    Given a plugin process was expected at PID <PID> and address <Network>:<Address>
    But `os.FindProcess(<PID>)` succeeds (e.g., PID reused or Unix behavior)
    And `net.Dial("<Network>", "<Address>")` fails (e.g., connection refused, timeout)
    When the ReattachFunc generated by `ReattachFunc(<PID>, "<Network>:<Address>")` is invoked
    Then the ReattachFunc should return an `ErrProcessNotFound` error (as a result of the dial failure)

  Scenario: CmdAttachedRunner Wait delegates to pidWait
    Given a CmdAttachedRunner instance initialized with a PID <PID>
    When its `Wait(ctx)` method is called
    Then the platform-specific `pidWait(<PID>)` function should be invoked
    And the error from `pidWait` should be returned
    # The specifics of pidWait (polling, OS calls) are platform-dependent and tested elsewhere.

  Scenario: CmdAttachedRunner Kill attempts to kill the process
    Given a CmdAttachedRunner instance initialized with a process handle for PID <PID>
    When its `Kill(ctx)` method is called
    Then `os.Process.Kill()` should be invoked on the stored process handle
    And the error from `Kill()` should be returned

  Scenario: CmdAttachedRunner ID returns the PID as a string
    Given a CmdAttachedRunner instance initialized with PID 12345
    When its `ID()` method is called
    Then it should return the string "12345"

  Scenario: CmdAttachedRunner uses identity address translation
    Given a CmdAttachedRunner instance
    When its `PluginToHost("tcp", "1.2.3.4:5678")` method is called
    Then it should return "tcp", "1.2.3.4:5678", nil
    When its `HostToPlugin("unix", "/tmp/s.sock")` method is called
    Then it should return "unix", "/tmp/s.sock", nil
