# Source: rpc_server.go
Feature: RPC Server Connection Handling and Service Dispensing (NetRPC)

  Background:
    The RPCServer component listens for client connections, manages multiplexed streams via yamux,
    and dispenses plugin services. Its reliability is key for cross-platform plugin operation.

  Scenario: RPCServer accepts a connection and sets up yamux server
    Given an RPCServer configured with plugins and stdio readers
    And a net.Listener "listener" is provided to the RPCServer's Serve method
    When a client connects to "listener"
    Then the RPCServer should accept the connection
    And a yamux.Server session should be established over this connection
    And the RPCServer should attempt to accept a control RPC stream via yamux
    And then accept stdout and stderr data streams via yamux

  Scenario: RPCServer handles yamux server setup failure on a new connection
    Given an RPCServer
    And a client connection that will cause yamux.Server setup to fail
    When the RPCServer attempts to serve this connection
    Then an error related to yamux server creation should be logged
    And the problematic connection should be closed

  Scenario: RPCServer handles failure to accept yamux control or data streams
    Given an RPCServer and a client connection with a successfully established yamux.Server "mux"
    And "mux.Accept()" will fail when attempting to accept the control or subsequent data streams
    When the RPCServer attempts to serve this yamux session
    Then an error related to accepting yamux streams should be logged
    And "mux" (and the underlying client connection) should be closed

  Scenario: RPCServer correctly serves Control and Dispenser services on the control stream
    Given an RPCServer has successfully accepted a client connection and all initial yamux streams (control, stdout, stderr)
    When the RPCServer sets up the RPC service for the control stream
    Then an RPC service named "Control" (implementing Ping, Quit) should be registered
    And an RPC service named "Dispenser" (implementing Dispense) should be registered
    And the RPC server should begin serving requests on the control stream

  Scenario: Control.Ping RPC call is handled successfully
    Given an RPCServer is serving a control connection
    When a client sends a "Control.Ping" RPC request
    Then the server should handle the request and return a success response (empty struct) without error

  Scenario: Control.Quit RPC call triggers server shutdown via DoneCh
    Given an RPCServer configured with a valid DoneCh channel
    And the server is serving a control connection
    When a client sends a "Control.Quit" RPC request
    Then the server's `done()` method should be called
    And the DoneCh channel should be closed
    And a success response should be returned for the Quit call

  Scenario: Dispenser.Dispense successfully prepares a plugin for serving
    Given an RPCServer configured with a "test_plugin" that has a valid Plugin.Server implementation
    And the RPCServer's MuxBroker is operational
    When a client sends a "Dispenser.Dispense" RPC request for "test_plugin"
    Then the "test_plugin"'s Plugin.Server method should be called
    And a unique stream ID should be generated by the MuxBroker and returned to the client
    And a new goroutine should be launched to:
      | Action                                                              |
      | Accept a new connection from the MuxBroker using the generated ID   |
      | Register the plugin's server implementation under the name "Plugin" |
      | Serve RPC requests for the plugin on this new connection            |
    # This ensures that each dispensed plugin gets its own communication channel.

  Scenario: Dispenser.Dispense handles unknown plugin name
    Given an RPCServer
    When a client sends a "Dispenser.Dispense" RPC request for "unknown_plugin"
    Then an error indicating "unknown plugin type: unknown_plugin" should be returned to the client

  Scenario: Dispenser.Dispense handles error from Plugin.Server method
    Given an RPCServer configured with a "faulty_plugin" whose Plugin.Server method returns an error "setup_failed"
    When a client sends a "Dispenser.Dispense" RPC request for "faulty_plugin"
    Then an error "setup_failed" should be returned to the client

  Scenario: RPCServer handles listener Accept errors
    Given an RPCServer's Serve method is running with a net.Listener "listener"
    When "listener.Accept()" returns an error (not net.ErrClosed)
    Then an error message should be logged
    And the Serve method should exit, triggering DoneCh closure
    When "listener.Accept()" returns net.ErrClosed (e.g., listener was closed)
    Then a debug message should be logged
    And the Serve method should exit, triggering DoneCh closure

  Scenario: RPCServer stdio streams copy data from server's configured readers
    Given an RPCServer has accepted yamux stdout and stderr streams ("plugin_stdout_stream", "plugin_stderr_stream")
    And the RPCServer is configured with s.Stdout reader "source_stdout" containing "hello stdout"
    And the RPCServer is configured with s.Stderr reader "source_stderr" containing "hello stderr"
    When data is processed
    Then "hello stdout" from "source_stdout" should be copied to "plugin_stdout_stream"
    And "hello stderr" from "source_stderr" should be copied to "plugin_stderr_stream"
    # This ensures that what the plugin writes (from its perspective) is correctly piped to the client.
